BEGIN;

-- =========================================================
-- ENUMS (existentes + POS/cajas que faltaban)
-- =========================================================
-- Del dominio "deportes/booking" (ya presentes en tu archivo)
CREATE TYPE IF NOT EXISTS booking_status            AS ENUM ('PENDING','CONFIRMED','CANCELED','COMPLETED','NO_SHOW');
CREATE TYPE IF NOT EXISTS booking_payment_method    AS ENUM ('ONLINE','INSITE');

CREATE TYPE IF NOT EXISTS day_of_week_enum          AS ENUM ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY');
CREATE TYPE IF NOT EXISTS active_state              AS ENUM ('ACTIVE','INACTIVE','MAINTENANCE');
CREATE TYPE IF NOT EXISTS enabled_flag              AS ENUM ('A','I');

CREATE TYPE IF NOT EXISTS media_type_enum           AS ENUM ('IMAGE','VIDEO','DOCUMENT','AUDIO');
CREATE TYPE IF NOT EXISTS media_category_enum       AS ENUM ('GALLERY','PROFILE','COVER','THUMBNAIL','DOCUMENT');

CREATE TYPE IF NOT EXISTS notification_type_enum    AS ENUM ('BOOKING_CONFIRMATION','BOOKING_REMINDER','BOOKING_CANCELLATION','PAYMENT_SUCCESS','PAYMENT_FAILED','PAYMENT_REMINDER','FACILITY_UPDATE','PROMOTION','SYSTEM_MAINTENANCE','WELCOME','PASSWORD_RESET','ACCOUNT_VERIFICATION','GENERAL');
CREATE TYPE IF NOT EXISTS priority_level_enum       AS ENUM ('LOW','NORMAL','HIGH','URGENT');
CREATE TYPE IF NOT EXISTS channel_type_enum         AS ENUM ('IN_APP','EMAIL','SMS','PUSH');
CREATE TYPE IF NOT EXISTS related_entity_type_enum  AS ENUM ('BOOKING','PAYMENT','FACILITY','USER','SPACE');
CREATE TYPE IF NOT EXISTS delivery_status_enum      AS ENUM ('PENDING','SENT','DELIVERED','FAILED','BOUNCED');

CREATE TYPE IF NOT EXISTS payment_method_enum       AS ENUM ('ONLINE','IN_PERSON');
CREATE TYPE IF NOT EXISTS payment_status_enum       AS ENUM ('PENDING','PAID','FAILED','CANCELED','REFUNDED');
CREATE TYPE IF NOT EXISTS payment_category_enum     AS ENUM ('CARD','BANK_TRANSFER','DIGITAL_WALLET','CASH','OTHER');

CREATE TYPE IF NOT EXISTS gender_enum               AS ENUM ('MALE','FEMALE','OTHER','NOT_SPECIFIED');
CREATE TYPE IF NOT EXISTS document_type_enum        AS ENUM ('IDENTITY_CARD','PASSPORT','LICENSE','OTHER');
CREATE TYPE IF NOT EXISTS civil_state_enum          AS ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED','COMMON-LAW');

CREATE TYPE IF NOT EXISTS rating_status_enum        AS ENUM ('PENDING','APPROVED','REJECTED','REPORTED');
CREATE TYPE IF NOT EXISTS facility_admin_role_enum  AS ENUM ('admin','manager','staff');

-- POS/Cajas que faltaban
CREATE TYPE IF NOT EXISTS product_type        AS ENUM ('PRODUCT','SERVICE');
CREATE TYPE IF NOT EXISTS movement_type_stock AS ENUM ('IN','OUT','ADJUSTMENT','TRANSFER');
CREATE TYPE IF NOT EXISTS status_purchase     AS ENUM ('DRAFT','POSTED','CANCELLED');
CREATE TYPE IF NOT EXISTS status_session      AS ENUM ('OPEN','CLOSED');
CREATE TYPE IF NOT EXISTS status_sale         AS ENUM ('DRAFT','POSTED','CANCELLED');
CREATE TYPE IF NOT EXISTS movement_type_cash  AS ENUM ('SALE_PAYMENT','CASH_IN','CASH_OUT','ADJUSTMENT');

-- =========================================================
-- TRIGGER genérico para updated_at
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- BLOQUE "DEPORTES / BOOKING"
-- =========================================================

-- Countries
CREATE TABLE IF NOT EXISTS dsg_bss_country (
  country_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country          VARCHAR(100) NOT NULL,
  iso_country      VARCHAR(3)   NOT NULL,
  phone_code       VARCHAR(10)  NOT NULL,
  iso_currency     VARCHAR(3)   NOT NULL,
  currency         VARCHAR(50)  NOT NULL,
  currency_simbol  VARCHAR(5)   NOT NULL,
  time_zone        VARCHAR(50)  NOT NULL,
  language         VARCHAR(10)  NOT NULL,
  date_format      VARCHAR(20)  NOT NULL,
  flag_url         VARCHAR(255) NOT NULL,
  user_create      VARCHAR(36)  NOT NULL, 
  user_update      VARCHAR(36),
  created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_department (
  dept_code  CHAR(10) PRIMARY KEY,
  country_id BIGINT NOT NULL REFERENCES dsg_bss_country(country_id),
  name       VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dsg_bss_province (
  dept_code  CHAR(10) NOT NULL,
  prov_code  CHAR(10) NOT NULL,
  name       VARCHAR(100) NOT NULL,
  ubigeo4    CHAR(20) GENERATED ALWAYS AS ((dept_code || prov_code)::CHAR(20)) STORED,
  CONSTRAINT dsg_bss_province_pk PRIMARY KEY (dept_code, prov_code),
  CONSTRAINT dsg_bss_province_dept_fk FOREIGN KEY (dept_code) REFERENCES dsg_bss_department(dept_code)
);

CREATE TABLE IF NOT EXISTS dsg_bss_district (
  dept_code  CHAR(10) NOT NULL,
  prov_code  CHAR(10) NOT NULL,
  dist_code  CHAR(10) NOT NULL,
  name       VARCHAR(120) NOT NULL,
  ubigeo6    CHAR(30) GENERATED ALWAYS AS ((dept_code || prov_code || dist_code)::CHAR(30)) STORED,
  CONSTRAINT dsg_bss_district_pk PRIMARY KEY (dept_code, prov_code, dist_code),
  CONSTRAINT dsg_bss_district_prov_fk FOREIGN KEY (dept_code, prov_code) REFERENCES dsg_bss_province(dept_code, prov_code)
);

-- Tabla de empresas y sucursales con recursividad a sí misma
CREATE TABLE IF NOT EXISTS dsg_bss_company (
  company_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id         BIGINT NOT NULL REFERENCES dsg_bss_country(country_id),
  tenant_id          VARCHAR(36) NOT NULL,
  name               VARCHAR(200) NOT NULL,
  address            TEXT NOT NULL,
  ubigeo_code        VARCHAR(20) NOT NULL,
  phone_cell         VARCHAR(20) NOT NULL,
  phone              VARCHAR(20) NOT NULL,
  website            VARCHAR(255),
  document           VARCHAR(20) NOT NULL,
  postal_code        VARCHAR(20),
  latitude           NUMERIC(10,8),
  longitude          NUMERIC(11,8),
  status             active_state DEFAULT 'ACTIVE',
  description        TEXT,
  parking_available  BOOLEAN DEFAULT FALSE,
  parent_company_id  BIGINT REFERENCES dsg_bss_company(company_id),
  is_enabled         enabled_flag NOT NULL,
  user_create        VARCHAR(36) NOT NULL,
  user_update        VARCHAR(36),
  created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_company_country ON dsg_bss_company(country_id);
CREATE INDEX IF NOT EXISTS idx_company_parent  ON dsg_bss_company(parent_company_id);

CREATE TABLE IF NOT EXISTS dsg_bss_facility_admins (
  admin_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id INTEGER NOT NULL,
  user_id     INTEGER,
  name        VARCHAR(100) NOT NULL,
  email       VARCHAR(100) NOT NULL UNIQUE,
  phone       VARCHAR(20),
  password    VARCHAR(255) NOT NULL,
  role        facility_admin_role_enum NOT NULL DEFAULT 'admin',
  permissions JSONB,
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_business_hour (
  hour_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id   VARCHAR(36) NOT NULL,
  day_of_week day_of_week_enum NOT NULL,
  start_time  TIME NOT NULL,
  end_time    TIME NOT NULL,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_business_hour_company ON dsg_bss_business_hour(company_id);

CREATE TABLE IF NOT EXISTS dsg_bss_person (
  persona_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER NOT NULL,
  country_id       BIGINT NOT NULL REFERENCES dsg_bss_country(country_id),
  first_name       VARCHAR(100) NOT NULL,
  last_name        VARCHAR(100) NOT NULL,
  email            VARCHAR(100) NOT NULL,
  phone            VARCHAR(20)  NOT NULL,
  date_birth       DATE,
  gender           gender_enum,
  document_type    document_type_enum,
  document_number  VARCHAR(50),
  address          TEXT,
  occupation       VARCHAR(100),
  civil_state      civil_state_enum,
  sports_preferences TEXT,
  accept_marketing BOOLEAN DEFAULT FALSE,
  is_banned        BOOLEAN DEFAULT FALSE,
  user_create      VARCHAR(36) NOT NULL,
  user_update      VARCHAR(36),
  created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  CONSTRAINT uq_person_email_phone UNIQUE (email, phone),
  CONSTRAINT uq_person_phone       UNIQUE (phone)
);
CREATE INDEX IF NOT EXISTS idx_person_country ON dsg_bss_person(country_id);
CREATE INDEX IF NOT EXISTS idx_person_user ON dsg_bss_person(user_id);

CREATE TABLE IF NOT EXISTS dsg_bss_client (
  client_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id            BIGINT NOT NULL REFERENCES dsg_bss_person(persona_id),
  client_code           VARCHAR(36) NOT NULL,
  client_name           VARCHAR(20) NOT NULL,
  password              VARCHAR(255) NOT NULL,
  url_recovery_password VARCHAR(255),
  is_enabled            enabled_flag NOT NULL,
  user_create           VARCHAR(36) NOT NULL,
  user_update           VARCHAR(36),
  created_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_client_persona ON dsg_bss_client(persona_id);

CREATE TABLE IF NOT EXISTS dsg_bss_user (
  user_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      VARCHAR(100) NOT NULL,
  last_name       VARCHAR(100) NOT NULL,
  email           VARCHAR(100) NOT NULL UNIQUE,
  phone           VARCHAR(20),
  password        VARCHAR(255),
  social_id       VARCHAR(255),
  social_provider VARCHAR(50),
  avatar_url      TEXT,
  registered_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
ALTER TABLE IF NOT EXISTS dsg_bss_person
  ADD CONSTRAINT fk_person_user FOREIGN KEY (user_id) REFERENCES dsg_bss_user(user_id);

CREATE TABLE IF NOT EXISTS dsg_bss_roles (
  role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name   VARCHAR(50) NOT NULL UNIQUE,
  description TEXT,
  permissions JSONB
);

CREATE TABLE IF NOT EXISTS dsg_bss_claim (
  claim_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(50) NOT NULL,
  code        VARCHAR(36) NOT NULL,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_role_claim (
  role_claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_id        INTEGER NOT NULL REFERENCES dsg_bss_roles(role_id),
  claim_id      INTEGER NOT NULL REFERENCES dsg_bss_claim(claim_id),
  name          VARCHAR(50) NOT NULL,
  description   TEXT NOT NULL,
  user_create   VARCHAR(36) NOT NULL,
  user_update   VARCHAR(36),
  created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_role_claim_rol   ON dsg_bss_role_claim(rol_id);
CREATE INDEX IF NOT EXISTS idx_role_claim_claim ON dsg_bss_role_claim(claim_id);

CREATE TABLE IF NOT EXISTS dsg_bss_user_roles (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES dsg_bss_user(user_id),
  role_id      INTEGER NOT NULL REFERENCES dsg_bss_roles(role_id),
  permissions_override JSONB,
  notes        TEXT,
  created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  CONSTRAINT unique_user_role_context UNIQUE (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON dsg_bss_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON dsg_bss_user_roles(role_id);

CREATE TABLE IF NOT EXISTS dsg_bss_sport_category (
  sport_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              VARCHAR(32) NOT NULL,
  name              VARCHAR(64) NOT NULL,
  created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_sport_type (
  sport_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(32) NOT NULL,
  name          VARCHAR(64) NOT NULL,
  created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_surface_type (
  surface_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR(32) NOT NULL,
  name            VARCHAR(64) NOT NULL,
  created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_space (
  space_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id              BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id               VARCHAR(36) NOT NULL,
  name                    VARCHAR(100) NOT NULL,
  surface_type_id         INTEGER NOT NULL REFERENCES dsg_bss_surface_type(surface_type_id),
  sport_type_id           INTEGER NOT NULL REFERENCES dsg_bss_sport_type(sport_type_id),
  sport_category_id       INTEGER NOT NULL REFERENCES dsg_bss_sport_category(sport_category_id),
  status_space            active_state NOT NULL,
  description             TEXT,
  capacity                INTEGER,
  dimensions              VARCHAR(100) NOT NULL,
  equipment               TEXT,
  hourly_rate             NUMERIC(10,2) NOT NULL,
  weekend_rate            NUMERIC(10,2) NOT NULL,
  peak_hour_rate          NUMERIC(10,2) NOT NULL,
  minimum_booking_minutes INTEGER DEFAULT 60,
  maximum_booking_minutes INTEGER DEFAULT 480,
  booking_buffer_minutes  INTEGER DEFAULT 15,
  user_create             VARCHAR(36) NOT NULL,
  user_update             VARCHAR(36),
  created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_space_company        ON dsg_bss_space(company_id);
CREATE INDEX IF NOT EXISTS idx_space_surface_type   ON dsg_bss_space(surface_type_id);
CREATE INDEX IF NOT EXISTS idx_space_sport_category ON dsg_bss_space(sport_category_id);
CREATE INDEX IF NOT EXISTS idx_space_sport_type     ON dsg_bss_space(sport_type_id);
CREATE INDEX IF NOT EXISTS idx_space_tenant         ON dsg_bss_space(tenant_id);

CREATE TABLE IF NOT EXISTS dsg_bss_media (
  media_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  space_id     BIGINT NOT NULL REFERENCES dsg_bss_space(space_id),
  tenant_id    VARCHAR(36) NOT NULL,
  type         media_type_enum DEFAULT 'IMAGE',
  category     media_category_enum DEFAULT 'GALLERY',
  file_url     VARCHAR(500) NOT NULL,
  file_name    VARCHAR(255) NOT NULL,
  description  TEXT,
  is_primary   BOOLEAN DEFAULT FALSE,
  user_create  VARCHAR(36) NOT NULL,
  user_update  VARCHAR(36),
  created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_media_tenant  ON dsg_bss_media(tenant_id);
CREATE INDEX IF NOT EXISTS idx_media_company ON dsg_bss_media(company_id);
CREATE INDEX IF NOT EXISTS idx_media_space   ON dsg_bss_media(space_id);

CREATE TABLE IF NOT EXISTS dsg_bss_favorite (
  favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   BIGINT NOT NULL REFERENCES dsg_bss_client(client_id),
  space_id    BIGINT NOT NULL REFERENCES dsg_bss_space(space_id),
  is_enabled  enabled_flag NOT NULL,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_favorite_client ON dsg_bss_favorite(client_id);
CREATE INDEX IF NOT EXISTS idx_favorite_space  ON dsg_bss_favorite(space_id);

CREATE TABLE IF NOT EXISTS dsg_bss_booking (
  booking_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id         BIGINT NOT NULL REFERENCES dsg_bss_client(client_id),
  space_id          BIGINT NOT NULL REFERENCES dsg_bss_space(space_id),
  tenant_id         VARCHAR(36) NOT NULL,
  booking_date      DATE NOT NULL,
  start_time        TIME NOT NULL,
  end_time          TIME NOT NULL,
  duration_minutes  INTEGER,
  duration_hours    NUMERIC(5,2),
  status            booking_status DEFAULT 'PENDING',
  payment_method    booking_payment_method NOT NULL,
  total_amount      NUMERIC(10,2) NOT NULL,
  discount_amount   NUMERIC(10,2) DEFAULT 0.00,
  notes             TEXT,
  cancellation_reason TEXT,
  confirmed_at      TIMESTAMP WITHOUT TIME ZONE,
  user_create       VARCHAR(36) NOT NULL,
  user_update       VARCHAR(36),
  created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_booking_client ON dsg_bss_booking(client_id);
CREATE INDEX IF NOT EXISTS idx_booking_space  ON dsg_bss_booking(space_id);

CREATE TABLE IF NOT EXISTS dsg_bss_payment_type (
  payment_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id      BIGINT NOT NULL REFERENCES dsg_bss_country(country_id),
  name            VARCHAR(100) NOT NULL,
  code            VARCHAR(50) NOT NULL,
  category        payment_category_enum NOT NULL,
  proveedor       VARCHAR(100) NOT NULL,
  descripcion     TEXT,
  payment_method  VARCHAR(1) NOT NULL,
  user_create     VARCHAR(36) NOT NULL,
  user_update     VARCHAR(36),
  created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payment_type_country ON dsg_bss_payment_type(country_id);

CREATE TABLE IF NOT EXISTS dsg_bss_configuration (
  configuration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id       BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id        VARCHAR(36) NOT NULL,
  iva              NUMERIC(10,3) NOT NULL,
  electronic_billing VARCHAR(1),
  user_create      VARCHAR(36) NOT NULL,
  user_update      VARCHAR(36),
  created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_configuration_company ON dsg_bss_configuration(company_id);

CREATE TABLE IF NOT EXISTS dsg_bss_configuration_payment (
  configuration_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id       BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id        VARCHAR(36) NOT NULL,
  payment_type_id  INTEGER NOT NULL REFERENCES dsg_bss_payment_type(payment_type_id),
  is_enabled       enabled_flag NOT NULL,
  user_create      VARCHAR(36) NOT NULL,
  user_update      VARCHAR(36),
  created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_configuration_payment_company ON dsg_bss_configuration_payment(company_id);
CREATE INDEX IF NOT EXISTS idx_configuration_payment_type    ON dsg_bss_configuration_payment(payment_type_id);

CREATE TABLE IF NOT EXISTS dsg_bss_notification (
  notification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id           BIGINT NOT NULL REFERENCES dsg_bss_client(client_id),
  company_id          BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id           VARCHAR(36) NOT NULL,
  title               VARCHAR(255) NOT NULL,
  message             TEXT NOT NULL,
  notification_type   notification_type_enum DEFAULT 'GENERAL',
  priority            priority_level_enum DEFAULT 'NORMAL',
  channel             channel_type_enum DEFAULT 'IN_APP',
  read_status         BOOLEAN DEFAULT FALSE,
  read_at             TIMESTAMP WITHOUT TIME ZONE,
  sent_at             TIMESTAMP WITHOUT TIME ZONE,
  scheduled_for       TIMESTAMP WITHOUT TIME ZONE,
  expires_at          TIMESTAMP WITHOUT TIME ZONE,
  related_entity_type related_entity_type_enum,
  action_url          VARCHAR(500),
  action_text         VARCHAR(100),
  delivery_status     delivery_status_enum DEFAULT 'PENDING',
  delivery_attempts   INTEGER DEFAULT 0,
  user_create         VARCHAR(36) NOT NULL,
  user_update         VARCHAR(36),
  created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notification_company ON dsg_bss_notification(company_id);
CREATE INDEX IF NOT EXISTS idx_notification_client  ON dsg_bss_notification(client_id);

CREATE TABLE IF NOT EXISTS dsg_bss_payment (
  payment_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id       BIGINT NOT NULL REFERENCES dsg_bss_booking(booking_id),
  payment_type_id  INTEGER NOT NULL REFERENCES dsg_bss_payment_type(payment_type_id),
  tenant_id        VARCHAR(36) NOT NULL,
  amount           NUMERIC(10,2) NOT NULL,
  method           payment_method_enum NOT NULL,
  status           payment_status_enum DEFAULT 'PENDING',
  payment_reference VARCHAR(255),
  transaction_id   VARCHAR(255),
  comision_aplicada NUMERIC(10,2) DEFAULT 0.00,
  moneda           VARCHAR(3) NOT NULL DEFAULT 'COP',
  payment_date     TIMESTAMP WITHOUT TIME ZONE,
  user_create      VARCHAR(36) NOT NULL,
  user_update      VARCHAR(36),
  created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payment_booking ON dsg_bss_payment(booking_id);
CREATE INDEX IF NOT EXISTS idx_payment_type    ON dsg_bss_payment(payment_type_id);

CREATE TABLE IF NOT EXISTS dsg_bss_rating (
  rating_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id      BIGINT NOT NULL REFERENCES dsg_bss_client(client_id),
  company_id     BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id      VARCHAR(36) NOT NULL,
  score          INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
  title          VARCHAR(200),
  comment        TEXT,
  would_recommend BOOLEAN DEFAULT TRUE,
  status         rating_status_enum DEFAULT 'PENDING',
  moderated_by   INTEGER,
  moderated_at   TIMESTAMP WITHOUT TIME ZONE,
  rated_at       TIMESTAMP WITHOUT TIME ZONE,
  user_create    VARCHAR(36) NOT NULL,
  user_update    VARCHAR(36),
  created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rating_client  ON dsg_bss_rating(client_id);
CREATE INDEX IF NOT EXISTS idx_rating_company ON dsg_bss_rating(company_id);
CREATE INDEX IF NOT EXISTS idx_rating_tenant  ON dsg_bss_rating(tenant_id);

-- =========================================================
-- POS: Horario caja (no conflictúa con dsg_bss_business_hour)
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_opening_hour (
  opening_hour_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
  open_time TIME NOT NULL,
  close_time TIME NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  CONSTRAINT uq_dsg_bss_opening_hour UNIQUE (company_id, weekday)
);

-- =========================================================
-- POS: Catálogos base
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_unit (
  unit_id BIGSERIAL PRIMARY KEY,
  code VARCHAR(16) UNIQUE NOT NULL,
  name VARCHAR(80) NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_tax_rates (
  tax_rate_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  code VARCHAR(30) UNIQUE NOT NULL,
  name VARCHAR(120) NOT NULL,
  rate NUMERIC(6,4) NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS dsg_bss_cash_register (
  cash_register_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- =========================================================
-- POS: Productos / Categorías / Impuestos por producto
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_categories (
  category_id BIGSERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS dsg_bss_product (
  product_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  category_id BIGINT REFERENCES dsg_bss_categories(category_id) ON DELETE SET NULL,
  sku VARCHAR(64) UNIQUE NOT NULL,
  barcode VARCHAR(64) UNIQUE,
  name VARCHAR(200) NOT NULL,
  type product_type NOT NULL DEFAULT 'PRODUCT',
  unit_id BIGINT REFERENCES dsg_bss_unit(unit_id),
  cost NUMERIC(12,4) DEFAULT 0,
  price NUMERIC(12,4) NOT NULL DEFAULT 0,
  is_stock_tracked BOOLEAN NOT NULL DEFAULT TRUE,
  min_stock NUMERIC(12,4) DEFAULT 0,
  notes VARCHAR(300),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_product_tax_rate (
  tenant_id VARCHAR(36) NOT NULL,
  product_id BIGINT NOT NULL REFERENCES dsg_bss_product(product_id) ON DELETE CASCADE,
  tax_rate_id BIGINT NOT NULL REFERENCES dsg_bss_tax_rates(tax_rate_id),
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  PRIMARY KEY (product_id, tax_rate_id)
);

-- =========================================================
-- POS: Inventario
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_location (
  location_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  code        VARCHAR(30) UNIQUE,
  name        VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS dsg_bss_warehouse (
  warehouse_id BIGSERIAL PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES dsg_bss_location(location_id),
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(120) NOT NULL,
  user_create VARCHAR(36) NOT NULL, 
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_warehouse UNIQUE (location_id, code)
);

-- CORRECCIÓN: agregar product_id + FK y mantener PK (warehouse_id, product_id)
CREATE TABLE IF NOT EXISTS dsg_bss_stock (
  warehouse_id BIGINT NOT NULL REFERENCES dsg_bss_warehouse(warehouse_id) ON DELETE CASCADE,
  product_id   BIGINT NOT NULL REFERENCES dsg_bss_product(product_id)     ON DELETE CASCADE,
  company_id   BIGINT,
  tenant_id    VARCHAR(36) NOT NULL,
  qty          NUMERIC(14,4) NOT NULL DEFAULT 0,
  user_create  VARCHAR(36) NOT NULL, 
  user_update  VARCHAR(36),
  created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  PRIMARY KEY (warehouse_id, product_id)
);

CREATE TABLE IF NOT EXISTS dsg_bss_stock_movement (
  stock_movement_id BIGSERIAL PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES dsg_bss_product(product_id),
  warehouse_id BIGINT NOT NULL REFERENCES dsg_bss_warehouse(warehouse_id),
  tenant_id VARCHAR(36) NOT NULL,
  movement_type movement_type_stock NOT NULL,
  qty NUMERIC(14,4) NOT NULL,
  unit_cost NUMERIC(12,4) DEFAULT 0,
  ref_table VARCHAR(50),
  ref_id BIGINT,
  happened_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  notes VARCHAR(300),
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sm_ref ON dsg_bss_stock_movement(ref_table, ref_id);
CREATE INDEX IF NOT EXISTS idx_sm_happened_at ON dsg_bss_stock_movement(happened_at);

-- =========================================================
-- POS: Proveedores y Compras
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_supplier (
  supplier_id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  name VARCHAR(200) NOT NULL,
  ruc VARCHAR(20),
  email VARCHAR(200),
  phone VARCHAR(40),
  address VARCHAR(250),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_purchase (
  purchase_id BIGSERIAL PRIMARY KEY,
  supplier_id BIGINT NOT NULL REFERENCES dsg_bss_supplier(supplier_id),
  warehouse_id BIGINT NOT NULL REFERENCES dsg_bss_warehouse(warehouse_id),
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  invoice_no VARCHAR(60),
  status status_purchase NOT NULL DEFAULT 'POSTED',
  subtotal NUMERIC(12,4) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  grand_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dsg_bss_purchase_item (
  purchase_item_id BIGSERIAL PRIMARY KEY,
  purchase_id BIGINT NOT NULL REFERENCES dsg_bss_purchase(purchase_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES dsg_bss_product(product_id),
  tenant_id VARCHAR(36) NOT NULL,
  qty NUMERIC(14,4) NOT NULL,
  unit_cost NUMERIC(12,4) NOT NULL,
  discount_amount NUMERIC(12,4) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,4) NOT NULL DEFAULT 0,
  total NUMERIC(12,4) NOT NULL,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
-- CORRECCIÓN: índice sobre la tabla correcta
CREATE INDEX IF NOT EXISTS idx_poi_purchase ON dsg_bss_purchase_item(purchase_id);

-- =========================================================
-- POS: Cajas (aperturas, movimientos), Ventas y Pagos
-- =========================================================
CREATE TABLE IF NOT EXISTS dsg_bss_cash_session (
  cash_session_id BIGSERIAL PRIMARY KEY,
  cash_register_id BIGINT NOT NULL REFERENCES dsg_bss_cash_register(cash_register_id),
  cashier_id BIGINT NOT NULL REFERENCES dsg_bss_user(user_id),
  opened_by BIGINT NOT NULL REFERENCES dsg_bss_user(user_id),
  closed_by BIGINT REFERENCES dsg_bss_user(user_id),
  company_id BIGINT NOT NULL REFERENCES dsg_bss_company(company_id),
  tenant_id VARCHAR(36) NOT NULL,
  shift_name VARCHAR(80),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ,
  opening_amount NUMERIC(12,4) NOT NULL DEFAULT 0,
  closing_amount NUMERIC(12,4),
  status status_session NOT NULL DEFAULT 'OPEN',
  total NUMERIC(12,4) NOT NULL DEFAULT 0,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_session_register_status ON dsg_bss_cash_session(cash_register_id, status);

CREATE TABLE IF NOT EXISTS dsg_bss_cash_movement (
  cash_movement_id BIGSERIAL PRIMARY KEY,
  cash_session_id BIGINT NOT NULL REFERENCES dsg_bss_cash_session(cash_session_id) ON DELETE CASCADE,
  tenant_id VARCHAR(36) NOT NULL,
  movement_type movement_type_cash NOT NULL,
  amount NUMERIC(12,4) NOT NULL,
  reason VARCHAR(200),
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cm_session ON dsg_bss_cash_movement(cash_session_id);

CREATE TABLE IF NOT EXISTS dsg_bss_sale (
  sale_id BIGSERIAL PRIMARY KEY,
  cash_session_id BIGINT REFERENCES dsg_bss_cash_session(cash_session_id),
  tenant_id VARCHAR(36) NOT NULL,
  status status_sale NOT NULL DEFAULT 'POSTED',
  subtotal NUMERIC(12,4) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  grand_total NUMERIC(12,4) NOT NULL DEFAULT 0,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes VARCHAR(300),
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sales_issued_at ON dsg_bss_sale(issued_at);

CREATE TABLE IF NOT EXISTS dsg_bss_sale_item (
  sale_item_id BIGSERIAL PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES dsg_bss_sale(sale_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES dsg_bss_product(product_id),
  tenant_id VARCHAR(36) NOT NULL,
  qty NUMERIC(14,4) NOT NULL,
  unit_price NUMERIC(12,4) NOT NULL,
  discount_amount NUMERIC(12,4) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,4) NOT NULL DEFAULT 0,
  total NUMERIC(12,4) NOT NULL,
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_si_sale ON dsg_bss_sale_item(sale_id);

CREATE TABLE IF NOT EXISTS dsg_bss_sale_payment (
  sale_payment_id BIGSERIAL PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES dsg_bss_sale(sale_id) ON DELETE CASCADE,
  payment_type_id INTEGER NOT NULL REFERENCES dsg_bss_payment_type(payment_type_id), -- CORRECCIÓN: INTEGER para alinear con FK
  cash_session_id BIGINT REFERENCES dsg_bss_cash_session(cash_session_id),
  tenant_id VARCHAR(36) NOT NULL, 
  amount NUMERIC(12,4) NOT NULL,
  paid_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reference VARCHAR(120),
  received_by BIGINT REFERENCES dsg_bss_user(user_id),
  user_create VARCHAR(36) NOT NULL,
  user_update VARCHAR(36),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_cash_link (
  tenant_id VARCHAR(36) NOT NULL,
  sale_payment_id BIGINT PRIMARY KEY REFERENCES dsg_bss_sale_payment(sale_payment_id) ON DELETE CASCADE,
  cash_movement_id BIGINT NOT NULL REFERENCES dsg_bss_cash_movement(cash_movement_id) ON DELETE CASCADE
);

-- =========================================================
-- VISTA: saldo de caja por sesión (JOIN corregido)
-- =========================================================
CREATE OR REPLACE VIEW v_cash_session_balance AS
SELECT
  cs.cash_session_id,
  cs.cash_register_id,
  cs.opened_at,
  cs.closed_at,
  cs.status,
  cs.opening_amount,
  COALESCE(SUM(CASE
    WHEN cm.movement_type = 'SALE_PAYMENT' THEN cm.amount
    WHEN cm.movement_type = 'CASH_IN'      THEN cm.amount
    WHEN cm.movement_type = 'CASH_OUT'     THEN -cm.amount
    WHEN cm.movement_type = 'ADJUSTMENT'   THEN cm.amount
    ELSE 0 END), 0) AS movement_net,
  (cs.opening_amount + COALESCE(SUM(CASE
    WHEN cm.movement_type = 'SALE_PAYMENT' THEN cm.amount
    WHEN cm.movement_type = 'CASH_IN'      THEN cm.amount
    WHEN cm.movement_type = 'CASH_OUT'     THEN -cm.amount
    WHEN cm.movement_type = 'ADJUSTMENT'   THEN cm.amount
    ELSE 0 END), 0)) AS expected_cash
FROM dsg_bss_cash_session cs
LEFT JOIN dsg_bss_cash_movement cm ON cm.cash_session_id = cs.cash_session_id
GROUP BY
  cs.cash_session_id, cs.cash_register_id, cs.opened_at, cs.closed_at, cs.status, cs.opening_amount;

-- =========================================================
-- TRIGGERS updated_at (solo tablas existentes)
-- =========================================================
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT unnest(ARRAY[
      -- dsg_bss_*
      'dsg_bss_country','dsg_bss_company','dsg_bss_business_hour','dsg_bss_person',
      'dsg_bss_client','dsg_bss_user','dsg_bss_rol','dsg_bss_claim','dsg_bss_role_claim',
      'dsg_bss_user_rol','dsg_bss_space','dsg_bss_media','dsg_bss_favorite','dsg_bss_booking',
      'dsg_bss_payment_type','dsg_bss_configuration','dsg_bss_configuration_payment',
      'dsg_bss_notification','dsg_bss_payment','dsg_bss_rating',
      -- POS / cajas / inventario
      'dsg_bss_opening_hour','dsg_bss_unit','dsg_bss_tax_rates','dsg_bss_cash_register',
      'dsg_bss_categories','dsg_bss_product','dsg_bss_product_tax_rate',
      'dsg_bss_location','dsg_bss_warehouse','dsg_bss_stock','dsg_bss_stock_movement',
      'dsg_bss_supplier','dsg_bss_purchase','dsg_bss_purchase_item',
      'dsg_bss_cash_session','dsg_bss_cash_movement','dsg_bss_sale','dsg_bss_sale_item','dsg_bss_sale_payment'
    ]) AS tbl
  LOOP
    EXECUTE format('
      DROP TRIGGER IF EXISTS trg_set_updated_at ON %I;
      CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    ', r.tbl, r.tbl);
  END LOOP;
END$$;

-- =========================================================
-- ÍNDICES RECOMENDADOS (rendimiento)
-- =========================================================
-- Movimientos de stock por almacén/producto/fecha
CREATE INDEX IF NOT EXISTS idx_sm_wh_prod_time
  ON dsg_bss_stock_movement(warehouse_id, product_id, happened_at);

-- Compras: búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_purchase_supplier   ON dsg_bss_purchase(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_warehouse  ON dsg_bss_purchase(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_purchase_date       ON dsg_bss_purchase(purchased_at);

-- Ítems de compra por producto
CREATE INDEX IF NOT EXISTS idx_poi_product ON dsg_bss_purchase_item(product_id);

-- Ventas por sesión de caja
CREATE INDEX IF NOT EXISTS idx_sale_session  ON dsg_bss_sale(cash_session_id);

-- Pagos de venta (consultas por venta/sesión)
CREATE INDEX IF NOT EXISTS idx_sp_sale    ON dsg_bss_sale_payment(sale_id);
CREATE INDEX IF NOT EXISTS idx_sp_session ON dsg_bss_sale_payment(cash_session_id);

-- Relación de impuestos por tasa
CREATE INDEX IF NOT EXISTS idx_ptr_tax ON dsg_bss_product_tax_rate(tax_rate_id);

COMMIT;
